src/Entity/Instansi.php
<?php

namespace App\Entity;

use App\Repository\InstansiRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InstansiRepository::class)
 */
class Instansi
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nama;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $alamat;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nomor_kontak;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nama_pimpinan;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tingkat;

    /**
     * @ORM\OneToMany(targetEntity=Layanan::class, mappedBy="instansi")
     */
    private $layanans;

    /**
     * @ORM\OneToMany(targetEntity=User::class, mappedBy="instansi")
     */
    private $users;

    public function __construct()
    {
        $this->layanans = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNama(): ?string
    {
        return $this->nama;
    }

    public function setNama(string $nama): self
    {
        $this->nama = $nama;

        return $this;
    }

    public function getAlamat(): ?string
    {
        return $this->alamat;
    }

    public function setAlamat(?string $alamat): self
    {
        $this->alamat = $alamat;

        return $this;
    }

    public function getNomorKontak(): ?string
    {
        return $this->nomor_kontak;
    }

    public function setNomorKontak(string $nomor_kontak): self
    {
        $this->nomor_kontak = $nomor_kontak;

        return $this;
    }

    public function getNamaPimpinan(): ?string
    {
        return $this->nama_pimpinan;
    }

    public function setNamaPimpinan(?string $nama_pimpinan): self
    {
        $this->nama_pimpinan = $nama_pimpinan;

        return $this;
    }

    public function getTingkat(): ?string
    {
        return $this->tingkat;
    }

    public function setTingkat(string $tingkat): self
    {
        $this->tingkat = $tingkat;

        return $this;
    }

    /**
     * @return Collection|Layanan[]
     */
    public function getLayanans(): Collection
    {
        return $this->layanans;
    }

    public function addLayanan(Layanan $layanan): self
    {
        if (!$this->layanans->contains($layanan)) {
            $this->layanans[] = $layanan;
            $layanan->setInstansi($this);
        }

        return $this;
    }

    public function removeLayanan(Layanan $layanan): self
    {
        if ($this->layanans->removeElement($layanan)) {
            // set the owning side to null (unless already changed)
            if ($layanan->getInstansi() === $this) {
                $layanan->setInstansi(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->nama;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setInstansi($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getInstansi() === $this) {
                $user->setInstansi(null);
            }
        }

        return $this;
    }

}

src/Form/InstansiType.php
<?php

namespace App\Form;

use App\Entity\Instansi;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InstansiType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nama')
            ->add('alamat')
            ->add('nomor_kontak')
            ->add('nama_pimpinan')
            ->add('tingkat')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Instansi::class,
        ]);
    }
}

src/Controller/InstansiController.php
<?php

namespace App\Controller;

use App\Entity\Instansi;
use App\Form\InstansiType;
use App\Repository\InstansiRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/instansi")
 */
class InstansiController extends AbstractController
{
    /**
     * @Route("/", name="instansi_index", methods={"GET"})
     */
    public function index(InstansiRepository $instansiRepository): Response
    {
        return $this->render('instansi/index.html.twig', [
            'instansis' => $instansiRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="instansi_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $instansi = new Instansi();
        $form = $this->createForm(InstansiType::class, $instansi);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($instansi);
            $entityManager->flush();

            return $this->redirectToRoute('instansi_index');
        }

        return $this->render('instansi/new.html.twig', [
            'instansi' => $instansi,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="instansi_show", methods={"GET"})
     */
    public function show(Instansi $instansi): Response
    {
        return $this->render('instansi/show.html.twig', [
            'instansi' => $instansi,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="instansi_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Instansi $instansi): Response
    {
        $form = $this->createForm(InstansiType::class, $instansi);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('instansi_index');
        }

        return $this->render('instansi/edit.html.twig', [
            'instansi' => $instansi,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="instansi_delete", methods={"POST"})
     */
    public function delete(Request $request, Instansi $instansi): Response
    {
        if ($this->isCsrfTokenValid('delete'.$instansi->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($instansi);
            $entityManager->flush();
        }

        return $this->redirectToRoute('instansi_index');
    }
}

templates/instansi/_delete_form.html.twig
<form method="post" action="{{ path('instansi_delete', {'id': instansi.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ instansi.id) }}">
    <button class="btn">Delete</button>
</form>

templates/instansi/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/instansi/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Instansi{% endblock %}

{% block body %}
    <h1>Edit Instansi</h1>

    {{ include('instansi/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('instansi_index') }}">back to list</a>

    {{ include('instansi/_delete_form.html.twig') }}
{% endblock %}

templates/instansi/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Instansi index{% endblock %}

{% block body %}
    <h1>Instansi index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nama</th>
                <th>Alamat</th>
                <th>Nomor_kontak</th>
                <th>Nama_pimpinan</th>
                <th>Tingkat</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for instansi in instansis %}
            <tr>
                <td>{{ instansi.id }}</td>
                <td>{{ instansi.nama }}</td>
                <td>{{ instansi.alamat }}</td>
                <td>{{ instansi.nomorKontak }}</td>
                <td>{{ instansi.namaPimpinan }}</td>
                <td>{{ instansi.tingkat }}</td>
                <td>
                    <a href="{{ path('instansi_show', {'id': instansi.id}) }}">show</a>
                    <a href="{{ path('instansi_edit', {'id': instansi.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('instansi_new') }}">Create new</a>
{% endblock %}

templates/instansi/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Instansi{% endblock %}

{% block body %}
    <h1>Create new Instansi</h1>

    {{ include('instansi/_form.html.twig') }}

    <a href="{{ path('instansi_index') }}">back to list</a>
{% endblock %}

templates/instansi/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Instansi{% endblock %}

{% block body %}
    <h1>Instansi</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ instansi.id }}</td>
            </tr>
            <tr>
                <th>Nama</th>
                <td>{{ instansi.nama }}</td>
            </tr>
            <tr>
                <th>Alamat</th>
                <td>{{ instansi.alamat }}</td>
            </tr>
            <tr>
                <th>Nomor_kontak</th>
                <td>{{ instansi.nomorKontak }}</td>
            </tr>
            <tr>
                <th>Nama_pimpinan</th>
                <td>{{ instansi.namaPimpinan }}</td>
            </tr>
            <tr>
                <th>Tingkat</th>
                <td>{{ instansi.tingkat }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('instansi_index') }}">back to list</a>

    <a href="{{ path('instansi_edit', {'id': instansi.id}) }}">edit</a>

    {{ include('instansi/_delete_form.html.twig') }}
{% endblock %}